### ISSUE TITLE
winlogbeat with input-beats doesn't work

### ISSUE THREAD

**Issue by AlexAkulov** [vjeantet/bitfan#19]
Hello! 
I tried to use winlogbeat with input-beats in bitfan but it doesn't work.
bitfan output:
```
[10.33.52.25:61701] Received unknown type (2J): <nil>
[10.33.52.25:61705] Received unknown type (2J): <nil>
[10.33.52.25:61710] Received unknown type (2J): <nil>
[10.33.52.25:61714] Received unknown type (2J): <nil>
```
winlogbeat config:
```
winlogbeat.event_logs:
  - name: Application
    ignore_older: 72h
  - name: Security
  - name: System
output.elasticsearch:
  enabled: false
output.logstash:
  enabled: true
  hosts: ["testelastic:5044"]
  worker: 1
  compression_level: 0
  ssl.enabled: false
output.console:
  enabled: false
  pretty: true
logging.level: info
logging.to_files: true
logging.files:
```
bitfan config:
```
input {
  beats {
    port => 5044
  }
}

output {
  stdout {
    codec => rubydebug {}
  }
}

```
